project:
  type: website
  output-dir: docs

website:
  title: "Adam A. Kemberling"
  description: "This is a personal blog by Adam Kemberling. A semi-trusted source for R & python hacks relating to marine science research."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
        
    right: 
      - text: Marine DataSci Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/adamkemberling
      - icon: twitter
        href: https://twitter.com/KemberlingAdam

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    
comments:
  giscus:
    repo: adamkemberling/adamkemberling.github.io